name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'docs/**', 'README.md' ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create Documentation Directory
        run: mkdir -p ./documentation

      # To keep FAA secret files
      - name: Make .faapriv directory
        run: mkdir .faapriv

      - name: Create .credentials file
        run: touch .faapriv/.credentials

      - name: Write .credentials file
        env:
          CREDENTIALS_SECRET: |
            ${{ secrets.CREDENTIALS }}
        run: echo "$CREDENTIALS_SECRET" > .faapriv/.credentials

      - name: Create .download_secrets file
        run: touch .faapriv/.download_secrets

      - name: Write .download_secrets file
        env:
          DOWNLOAD_SECRETS_SECRET: |
            ${{ secrets.DOWNLOAD_SECRETS }}
        run: echo "$DOWNLOAD_SECRETS_SECRET" > .faapriv/.download_secrets

      - name: Create .secrets file
        run: touch .faapriv/.secrets

      - name: Write .secrets file
        env:
          SECRETS_SECRET: |
            ${{ secrets.SECRETS }}
        run: echo "$SECRETS_SECRET" > .faapriv/.secrets

      - name: Create keystore.properties file
        run: touch .faapriv/keystore.properties

      - name: Write keystore.properties file
        env:
          KEYSTORE_PROPS_SECRET: |
            ${{ secrets.KEYSTORE_PROPERTIES }}
        run: echo "$KEYSTORE_PROPS_SECRET" > .faapriv/keystore.properties

      - name: LS Root
        run: ls -la .faapriv

      - name: LS FAA Priv
        run: ls -la .faapriv

      - name: CAT keystore.properties
        run: cat .faapriv/keystore.properties

      - name: Create Debug Keystore
        id: create_debug_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'faa_android_debug_keystore.jks'
          encodedString: ${{ secrets.DEBUG_KEYSTORE }}

      - name: Copy Debug Keystore file to .faapriv
        run: cp ${{ steps.create_debug_keystore.outputs.filePath }} .faapriv

      - name: Create Release Keystore
        id: create_release_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'faa_android_release_keystore.jks'
          encodedString: ${{ secrets.RELEASE_KEYSTORE }}

      - name: Copy Release Keystore file to .faapriv
        run: cp ${{ steps.create_release_keystore.outputs.filePath }} .faapriv

      - name: Generate Dokka Documentation
        run: |
          ./gradlew dokkaGfm

      - name: Remove .faapriv
        run: |
          rm -rf .faapriv

      - name: Generate SDK documentation
        run: |
          VERSION=$(git tag --sort=committerdate | tail -1)
          echo Generating API documentation for version $VERSION
          gradle -Pversion=$VERSION dokkaGfm

      - name: Copying README to documentation
        run: |
          echo copying
          cp "README.md" "./documentation/integration_guide.md"

      - name: Commit Documentation
        run: |
          git checkout master
          git config --global user.email "mail-admin@faurecia-aptoide.com"
          git config --global user.name "Faurecia Aptoide Automotive"
          git add .
          git diff-index --quiet HEAD || git commit -am "Automated Dokka documentation"
          git push origin master
